-- Borra las tablas antiguas para asegurar una instalación limpia
DROP TABLE IF EXISTS public.documentos;
DROP TABLE IF EXISTS public.evaluaciones;
DROP TABLE IF EXISTS public.proveedores;

-- Crea la tabla 'proveedores' con nombres de columna estandarizados (snake_case)
CREATE TABLE public.proveedores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_unit TEXT,
    supplier_number TEXT,
    nombre TEXT,
    alternate_name TEXT,
    rfc TEXT,
    site TEXT,
    status TEXT,
    address1 TEXT,
    address2 TEXT,
    address3 TEXT,
    city TEXT,
    state TEXT,
    county TEXT,
    postal_code TEXT,
    payment_terms TEXT,
    currency TEXT,
    remittance_email TEXT,
    primary_flag TEXT,
    purchasing_email TEXT,
    fecha_alta TIMESTAMPTZ DEFAULT now(),
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Crea la tabla 'evaluaciones' con nombres de columna estandarizados
CREATE TABLE public.evaluaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proveedor_id BIGINT REFERENCES public.proveedores(id) ON DELETE CASCADE,
    tipo_evaluacion TEXT,
    puntaje INT,
    criterios JSONB,
    comentarios TEXT,
    fecha TIMESTAMPTZ DEFAULT now(),
    created_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE (proveedor_id, tipo_evaluacion)
);

-- Crea la tabla 'documentos' con nombres de columna estandarizados
CREATE TABLE public.documentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proveedor_id BIGINT REFERENCES public.proveedores(id) ON DELETE CASCADE,
    tipo TEXT,
    nombre_archivo TEXT,
    storage_path TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE (proveedor_id, tipo)
);

CREATE TABLE IF NOT EXISTS criterios (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    ponderacion INTEGER NOT NULL,
    tipo_evaluacion VARCHAR(50) NOT NULL -- 'ALTA' o 'INTERNA'
);

-- Insertar criterios iniciales
INSERT INTO criterios (nombre, ponderacion, tipo_evaluacion) VALUES
('Carta Opinión Positiva del mes en curso', 10, 'ALTA'),
('Estado de Cuenta (no mayor a 3 meses)', 10, 'ALTA'),
('Constancia de Situación Fiscal', 10, 'ALTA'),
('Comprobante de Domicilio', 6, 'ALTA'),
('Formato Alta de Proveedores', 5, 'INTERNA'),
('Verificación de Dirección Física', 10, 'INTERNA'),
('Contactos de Ventas/Finanzas (2 o más)', 5, 'INTERNA'),
('Legitimidad de Papelería', 10, 'INTERNA'),
('Referencias de Clientes', 6, 'INTERNA'),
('Acta Constitutiva', 6, 'INTERNA'),
('Registro Patronal', 5, 'INTERNA'),
('Estados Financieros', 5, 'INTERNA'),
('INE del Representante Legal', 6, 'INTERNA');

-- Re-crea y activa las políticas de seguridad para todas las tablas
CREATE POLICY "Public Full Access for Proveedores" ON public.proveedores FOR ALL USING (true) WITH CHECK (true);
ALTER TABLE public.proveedores ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Full Access for Evaluaciones" ON public.evaluaciones FOR ALL USING (true) WITH CHECK (true);
ALTER TABLE public.evaluaciones ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Full Access for Documentos" ON public.documentos FOR ALL USING (true) WITH CHECK (true);
ALTER TABLE public.documentos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Full Access for Criterios" ON public.criterios FOR ALL USING (true) WITH CHECK (true);
ALTER TABLE public.criterios ENABLE ROW LEVEL SECURITY;
