-- Borra las tablas antiguas para asegurar una instalación limpia
DROP TABLE IF EXISTS public.documentos;
DROP TABLE IF EXISTS public.evaluaciones;
DROP TABLE IF EXISTS public.proveedores;

-- Crea la tabla 'proveedores' con nombres de columna estandarizados (snake_case)
CREATE TABLE public.proveedores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_unit TEXT,
    supplier_number TEXT,
    nombre TEXT,
    alternate_name TEXT,
    rfc TEXT,
    site TEXT,
    status TEXT,
    address1 TEXT,
    address2 TEXT,
    address3 TEXT,
    city TEXT,
    state TEXT,
    county TEXT,
    postal_code TEXT,
    payment_terms TEXT,
    currency TEXT,
    remittance_email TEXT,
    primary_flag TEXT,
    purchasing_email TEXT,
    fecha_alta TIMESTAMPTZ DEFAULT now(),
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Crea la tabla 'evaluaciones' con nombres de columna estandarizados
CREATE TABLE public.evaluaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proveedor_id BIGINT REFERENCES public.proveedores(id) ON DELETE CASCADE,
    tipo_evaluacion TEXT,
    puntaje INT,
    criterios JSONB,
    comentarios TEXT,
    fecha TIMESTAMPTZ DEFAULT now(),
    created_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE (proveedor_id, tipo_evaluacion)
);

-- Crea la tabla 'documentos' con nombres de columna estandarizados
CREATE TABLE public.documentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proveedor_id BIGINT REFERENCES public.proveedores(id) ON DELETE CASCADE,
    tipo TEXT,
    nombre_archivo TEXT,
    contenido TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE (proveedor_id, tipo)
);

-- Re-crea y activa las políticas de seguridad para todas las tablas
CREATE POLICY "Public Full Access for Proveedores" ON public.proveedores FOR ALL USING (true) WITH CHECK (true);
ALTER TABLE public.proveedores ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Full Access for Evaluaciones" ON public.evaluaciones FOR ALL USING (true) WITH CHECK (true);
ALTER TABLE public.evaluaciones ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Full Access for Documentos" ON public.documentos FOR ALL USING (true) WITH CHECK (true);
ALTER TABLE public.documentos ENABLE ROW LEVEL SECURITY;
